###**Questions 1:**

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [ ]:
import numpy as np

In [ ]:
np_array = np.arange(2, 50, 3)
print(np_array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


###**Questions 2:**

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [ ]:
#Accept two lists of 5 elements
list1 = list(map(str, input().split()))[:5]
list2 = list(map(str, input().split()))[:5]

#Convert arrays into Numpy array
new_list1 = np.array(list1)
new_list2 = np.array(list2)

one two three four five
six seven eight nine ten


In [ ]:
#Conactenate arrays
concat = np.char.add(new_list1, new_list2)
concat

array(['onesix', 'twoseven', 'threeeight', 'fournine', 'fiveten'],
      dtype='<U10')

In [ ]:
#Sort arrays
print(np.sort(new_list1))
print(np.sort(new_list2))

['five' 'four' 'one' 'three' 'two']
['eight' 'nine' 'seven' 'six' 'ten']


###**Questions 3:**

Write a code snippet to find the dimensions of a ndarray and its size.

In [ ]:
#Create np array
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
#Print dimension of ndarray
print(arr.ndim)

#print size of ndarray
print(arr.size)

2
6


###**Questions 4:**

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [ ]:
#Create 1D array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Convert 1D array to a 2D numpy array 
arr_2d = np.reshape(arr, (2, 5))

print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


###**Questions 5:**

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [ ]:
#Create array 1
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
#Convert to square array
new_arr1 = np.square(arr1)

#Create array 2
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
#Convert to square array
new_arr2 = np.square(arr2)

In [ ]:
#Convert to vstack
print(np.vstack((new_arr1, new_arr2)))

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]


In [ ]:
#Convert to hstack
print(np.hstack((new_arr1, new_arr2)))

[[  1   4   9  49  64  81]
 [ 16  25  36 100 121 144]]


###**Questions 6:**

How to get unique items and counts of unique items?

In [ ]:
#Create np array
arr = np.array([1, 2, 3, 4, 1, 6, 2, 5, 4])

#Find Unique items
print(np.unique(arr))

#Count of unique items
print(len(np.unique(arr)))

[1 2 3 4 5 6]
6
